* Fixed exitcode bug
git-svn-id: https://the.narro.ws/svn/brimstone/etc/zsh@527 9fd2b4f7-785e-4997-ad42-798039e1f157

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,13 +1,13 @@
 # our precmd runs first, as it build up the PROMPT variable
 precmd_main () {
-	# Capture our exit code
-	local exitcode=$?
 	# Figure out our left primary output
 	# Now that we have all of our variables set, let our theme compute it's prompt
 	theme_prompt
 }
 
 function precmd {
+	# Capture our exit code
+	local exitcode=$?
 	# run all of our precmd functions setup for us
 	for ((i=1; i <= ${#precmd_funcs}; i+=1)); do
 		$precmd_funcs[$i]
