Issue 15: Fixed the error message if file:// is not a directory.

diff --git a/init b/init
--- a/init
+++ b/init
@@ -250,7 +250,7 @@ function myzsh {
 					elif [ ${repo%%://*} = "https" ]; then
 						git clone "$repo" || svn co "$repo" || echo "Error accessing $repo via git and svn"
 					elif [ ${repo%%://*} = "file" ]; then
-						[ -d ${repo#file://*} ] && cp -R ${repo#file://*} . || echo "Error not a directory"
+						[ -d ${repo#file://*} ] && cp -R ${repo#file://*} . || echo "Error remote must be a directory"
 					fi
 					popd &>/dev/null
 				done
