Issue #15: Added ability to use a local directory as a remote.

diff --git a/init b/init
--- a/init
+++ b/init
@@ -249,6 +249,8 @@ function myzsh {
 						git clone "$repo" || svn co "$repo" || echo "Error accessing $repo via git and svn"
 					elif [ ${repo%%://*} = "https" ]; then
 						git clone "$repo" || svn co "$repo" || echo "Error accessing $repo via git and svn"
+					elif [ ${repo%%://*} = "file" ]; then
+						[ -d ${repo#file://*} ] && cp -R ${repo#file://*} . || echo "Error not a directory"
 					fi
 					popd &>/dev/null
 				done
